sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.local
    - vendor

env:
  global:
    - COMPOSER_ARGS="--no-interaction"
    - COVERAGE_DEPS="satooshi/php-coveralls"
    - LEGACY_DEPS="phpunit/phpunit"

matrix:
  include:
    - php: 5.6
      env:
        - DEPS=lowest
    - php: 5.6
      env:
        - DEPS=locked
        - TEST_COVERAGE=true
    - php: 5.6
      env:
        - DEPS=latest
    - php: 7
      env:
        - DEPS=lowest
    - php: 7
      env:
        - DEPS=locked
        - CS_CHECK=true
    - php: 7
      env:
        - DEPS=latest
    - php: 7.1
      env:
        - DEPS=lowest
    - php: 7.1
      env:
        - DEPS=locked
    - php: 7.1
      env:
        - DEPS=latest
    - php: hhvm
      env:
        - DEPS=lowest
    - php: hhvm
      env:
        - DEPS=locked
    - php: hhvm
      env:
        - DEPS=latest
  allow_failures:
    - php: hhvm

before_install:
  - if [[ $TEST_COVERAGE != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi
  - travis_retry composer self-update

install:
  - travis_retry composer install $COMPOSER_ARGS --ignore-platform-reqs
  - if [[ $TRAVIS_PHP_VERSION =~ ^5.6 ]]; then travis_retry composer update $COMPOSER_ARGS --with-dependencies $LEGACY_DEPS ; fi
  - if [[ $DEPS == 'latest' ]]; then travis_retry composer update $COMPOSER_ARGS ; fi
  - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --prefer-lowest --prefer-stable $COMPOSER_ARGS ; fi
  - if [[ $TEST_COVERAGE == 'true' ]]; then travis_retry composer require --dev $COMPOSER_ARGS $COVERAGE_DEPS ; fi
  - composer show

script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then composer test-coverage ; else composer test ; fi
  - if [[ $CS_CHECK == 'true' ]]; then composer cs-check ; fi
  - if [[ $CS_CHECK == 'true' ]]; then composer license-check ; fi

after_script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then composer upload-coverage ; fi

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#zftalk.dev"
    on_success: change
    on_failure: always
  slack:
    rooms:
      - secure: "MZggsHrpmr9k5jyQDfQJzWLGBrwhE2QfAlSgCWLAPrp2W9CehXXMpDniuWTaZzjj1pZNhJzetNshNJU9CVtq0Jqels8DRK9oJoX3VZqWGW7pugDDBXNi7SnPcjOs0rSYCmf+g/cGTr4m7KJXWJDmmJtipJtmE14vwWVcPTOE9RXWcUMyNKwyfzTiAT1Uh7eau7swenb2+eU5PwkFaGoRtiJWjJrzB+HwVcV6o589O6dkG244TDWlAFulpLajYKn/ia09j6bcKqjTowyMk6i2FKwUNW3+ZYHIkx1vG3b94mLOWJnIMEhKTDxBn/vRTSWegrLf4ECbDb04NbEzl6j+WmPDL25h1MTMBALcLaCVE1S4i7S/eAnXdUfR/j6hn97m1xKMVkHtYOtV+VNMR71fvTlojnI2OZp+nQTZVMDGwBiaraj46Yt0z7rYcLy1WSA0qSiya84/bm+PEcqbuFg0v/Og4JrxtUl8ujaqPmSjR/bVm0fJbxLnM+MB8lVtHBr+pVuVMePTnxrKo1xo8C5NGHpw7HRjl7FG/hDLrAF3XQ7pawVU/gWz70wcF0439FhISdBq60SWw9bGndpfn1MMZlwMoUGhM+guyOocJv1/dUhZDqbL5js5HUuIpzqOG27UPN2icL55FOMLVVL4szLGab/pUonGM93VTbxvQVLzNuc="
    on_success: change
    on_failure: always
